export enum ROLES {
  RESCUE_ROLE = "RESCUE_ROLE",
  WITHDRAW_ROLE = "WITHDRAW_ROLE",
  GOVERNANCE_ROLE = "GOVERNANCE_ROLE",
  WATCHER_ROLE = "WATCHER_ROLE",
  TRANSMITTER_ROLE = "TRANSMITTER_ROLE",
  SWITCHBOARD_DISABLER_ROLE = "SWITCHBOARD_DISABLER_ROLE",
}
